defaults:
  - agent: ppo_ff_world_model # ppo_ff_world_model, ppo_byol_explore, ppo_byol_hindsight 

name: CuriousAgents
env_name: MountainCar-v0 #  Minecraft2D # Maze-v0 # 
train: True
load_state: False
visualise: True
visualisation_steps: 200
log_dir: "./logs"
training_steps: 1e7
seed: 1234