defaults:
  - agent: ppo_boyl_explore #  ppo_ff_world_model #

name: CuriousAgents
env_name: Maze-v0 # MountainCar-v0 # 
train: True
load_state: False
visualise: False
log_dir: "./logs"
training_steps: 8.8e6 # 2e7 # 
seed: 1234567