defaults:
  - agent: ppo_ff_world_model # ppo_boyl_explore # 

name: CuriousAgents
env_name: MountainCar-v0 # Maze-v0 # 
train: True
load_state: False
visualise: False
log_dir: "./logs"
training_steps: 1e7 # 8.8e6
seed: 123456