defaults:
  - agent: ppo_boyl_hindsight # ppo_boyl_explore #  ppo_ff_world_model #

name: CuriousAgents
env_name: Minecraft2D # Maze-v0 # MountainCar-v0 # 
train: True
load_state: False
visualise: True
visualisation_steps: 200
log_dir: "./logs"
training_steps: 1e8 # 8.8e6 # 2e7 # 
seed: 1234